import React from 'react'
import { StatusBar } from '../components/PhoneFrame'
import { NB, NB_BORDER, hardShadow } from '../styles/neoBrutalism'

const EFFECTIVE_DATE = 'July 15, 2026'
const CONTACT_EMAIL = 'support@missvfit.app'

// Plain-language sections for both documents — kept in one file so the two
// docs stay consistent in tone/structure and so Settings + the signup
// consent line can share the exact same content.
const TERMS_SECTIONS = [
  { h: 'Agreement to Terms', body: `By creating a MissVfit account or using the app, you agree to these Terms of Service. If you don't agree, please don't use MissVfit.` },
  { h: 'Not medical advice', body: `MissVfit generates workout and nutrition suggestions based on the information you provide. It is not a medical device and does not provide medical advice, diagnosis, or treatment. Talk to a doctor before starting a new exercise or nutrition program, especially if you're pregnant, injured, or managing a health condition.` },
  { h: 'Your account', body: `You're responsible for keeping your login credentials secure and for all activity under your account. You must be at least 16 years old to use MissVfit.` },
  { h: 'MissVfit Pro & billing', body: `MissVfit Pro is a paid subscription that unlocks AI nutrition features (meal suggestions, food lookup, and meal adjustments). Subscriptions are billed and managed through Stripe, our payment processor — MissVfit never sees or stores your card details. Subscriptions renew automatically until cancelled; you can cancel anytime from Settings → Manage Subscription.` },
  { h: 'AI-generated content', body: `Meal ideas and macro estimates are generated by an AI model (Anthropic's Claude) and may occasionally be inaccurate or incomplete. Use your own judgment, especially around allergies and medical conditions — always double-check ingredients yourself.` },
  { h: 'Acceptable use', body: `Don't misuse MissVfit — that includes trying to break or bypass the app's security, uploading content that harms or harasses other users, or using the social feed to post anything illegal, abusive, or infringing.` },
  { h: 'Your content', body: `You keep ownership of the photos, posts, and text you upload. By posting to the community feed, you allow other MissVfit users to see that content within the app.` },
  { h: 'Termination', body: `You can stop using MissVfit and delete your account at any time by contacting us. We may suspend accounts that violate these terms.` },
  { h: 'Disclaimer & liability', body: `MissVfit is provided "as is" without warranties of any kind. To the fullest extent permitted by law, MissVfit isn't liable for indirect or incidental damages arising from your use of the app.` },
  { h: 'Changes to these terms', body: `We may update these Terms occasionally. Continued use of MissVfit after a change means you accept the updated terms.` },
  { h: 'Contact', body: `Questions about these Terms? Email ${CONTACT_EMAIL}.` },
]

const PRIVACY_SECTIONS = [
  { h: 'Overview', body: `This Privacy Policy explains what information MissVfit collects, how it's used, and who it's shared with. MissVfit is a strength & nutrition app, so some of what we collect — body weight, progress photos, workout history, dietary needs — is health-related information. We treat it accordingly.` },
  { h: 'Information we collect', body: `Account info: your name, email, and username.\nOnboarding & fitness data: physique goal, experience level, equipment, target areas, injuries, dietary preferences, and allergies.\nProgress data: workout history, body weight entries, and any progress photos you choose to upload.\nNutrition data: meals you log or describe, including free-text descriptions of food you've eaten.\nSocial content: posts, captions, reactions, and friend connections you create in the Discover feed.\nDevice info: a push-notification token, if you enable reminders.` },
  { h: 'Third-party AI processing (Anthropic)', body: `When you ask for a meal suggestion, look up a food, describe something you've already eaten, or ask for a meal adjustment, that text — along with relevant profile context like your dietary preferences and allergies — is sent to Anthropic (the maker of Claude) to generate a response. This request goes through our own server, never directly from your device with your API key. Anthropic processes this data to return the AI response and does not use it to train their models under our commercial agreement. No progress photos or body-weight numbers are ever sent to Anthropic — only text you type or the meal/food context needed to answer your request.` },
  { h: 'Other service providers', body: `Supabase hosts our database, authentication, and file storage (including progress photos and post media). Stripe processes MissVfit Pro subscription payments — MissVfit never receives or stores your full card number. If you enable push notifications, your device's push token is used solely to deliver reminders.` },
  { h: 'How we use your information', body: `To build your personalised workout and nutrition plan, track your progress, power the social feed, process your subscription, and send reminders you've opted into. We don't sell your personal information.` },
  { h: 'Who can see your content', body: `Progress photos and body-weight entries are private to you. Posts you choose to share to the Discover feed (workout or meal posts, including any photo/video you attach) are visible to other MissVfit users per the feed you post to (Global or Friends).` },
  { h: 'Data retention & deletion', body: `We keep your data for as long as your account is active. To delete your account and associated data, email ${CONTACT_EMAIL} — we'll process the request within 30 days.` },
  { h: 'Your rights', body: `You can access, correct, or export most of your data directly in the app (Profile, Body Progress, Settings). For anything else — including a full data export or deletion request — contact us at ${CONTACT_EMAIL}.` },
  { h: "Children's privacy", body: `MissVfit is not directed at children under 16, and we don't knowingly collect data from anyone under that age.` },
  { h: 'Changes to this policy', body: `We may update this Privacy Policy from time to time. We'll update the effective date below when we do.` },
  { h: 'Contact', body: `Questions about this Privacy Policy? Email ${CONTACT_EMAIL}.` },
]

const DOCS = {
  terms: { title: 'Terms of Service', sections: TERMS_SECTIONS },
  privacy: { title: 'Privacy Policy', sections: PRIVACY_SECTIONS },
}

export default function LegalDoc({ doc = 'terms', onBack }) {
  const { title, sections } = DOCS[doc] || DOCS.terms

  return (
    <>
      <StatusBar />
      <div style={{ padding: '10px 22px 6px', flexShrink: 0, display: 'flex', alignItems: 'center', gap: 10 }}>
        <button onClick={onBack} style={{ width: 38, height: 38, borderRadius: 12, border: NB_BORDER, background: NB.white, boxShadow: hardShadow(2), display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', flexShrink: 0 }}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke={NB.ink} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="15 18 9 12 15 6"/></svg>
        </button>
        <div style={{ fontFamily: NB.fontDisplay, fontWeight: 900, fontSize: 22, textTransform: 'uppercase', color: NB.ink }}>{title}</div>
      </div>

      <div style={{ flex: 1, overflowY: 'auto', padding: '10px 22px 32px' }}>
        <div style={{ fontSize: 12, color: '#555', marginBottom: 18 }}>Effective {EFFECTIVE_DATE}</div>
        {sections.map(({ h, body }) => (
          <div key={h} style={{ marginBottom: 20 }}>
            <div style={{ fontFamily: NB.fontDisplay, fontWeight: 800, fontSize: 15, color: NB.ink, marginBottom: 6 }}>{h}</div>
            {body.split('\n').map((line, i) => (
              <div key={i} style={{ fontSize: 13, color: '#333', lineHeight: 1.6, marginBottom: 4 }}>{line}</div>
            ))}
          </div>
        ))}
      </div>
    </>
  )
}
